# ============================
# Local server configuration
# ============================

[server]

name = "irc-rabat"
host = "0.0.0.0"
port = 6667
password = "1234"

# ============================
# Network configuration
# ============================

[network]

name = "MyIRC"
max_clients = 1000
max_channels_per_user = 20
max_nickname_length = 16
max_message_length = 512

# ============================
# Operators
# ============================

[[operator]

nickname = "admin"
password = "admin-password" #sjdadkasd

[[operator]]

nickname = "moderator"
password = "mod-password"

# ============================
# Linked servers
# ============================

[[link]]

name = "irc-paris"
host = "192.168.1.10"
port = 6668
password = "paris-secret"
auto_connect = true
retry_interval = 30

[[link]]

name = "irc-berlin"
host = "192.168.1.11"
port = 6669
password = "berlin-secret"
auto_connect = false
retry_interval = 60
